# Generated by Django 3.1.1 on 2020-10-02 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=6)),
                ('college', models.CharField(max_length=30)),
                ('height', models.CharField(max_length=4)),
                ('classof', models.CharField(max_length=6)),
                ('position_rank', models.IntegerField()),
                ('year_rank', models.IntegerField()),
                ('player_img', models.ImageField(default='default.jpg', upload_to='player_pics')),
                ('biography', models.CharField(max_length=400)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='draft.year')),
            ],
        ),
    ]
