# Generated by Django 3.1.1 on 2020-10-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_remove_player_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='biography',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
